[package]
name = "day2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc_driver = "0.2.2"
serde = "1.0.148"
serde_derive = "1.0.148"
